version: "3"

services:

  sqlite_reader:
    build: .
    container_name: sqlite_reader
    volumes:
      - .:/code
    ports:
      - 8000:8000
    restart: on-failure:3
    command: >
      sh -c "uvicorn --app-dir app/ main:app --host 0.0.0.0 --port 8000 --reload"